name: Eslint!
'on':
  - pull_request

setup:
  checkout:
    - uses: actions/checkout@v1
      name: get the repo
  yarn:
    setup: checkout
    steps:
      - run: yarn
        name: install dependencies

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: Khan/flow-coverage-action@2d18e7cda7142361a1629a3aca95df985db0a432
        setup: yarn
        with:
          flow-bin: ./node_modules/.bin/flow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: Khan/jest-action@master
        setup: yarn
        with:
          jest-bin: ./node_modules/.bin/jest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: Khan/eslint-action@master
        setup: yarn
        with:
          eslint-lib: ./node_modules/eslint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn flow --color always
        setup: yarn
